# Generated by Django 5.0 on 2024-02-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('music', models.FileField(upload_to='Music')),
                ('cover', models.FileField(upload_to='Music/Cover')),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unwind.mood')),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unwind.musiccategory')),
            ],
        ),
    ]
