# Generated by Django 5.0.2 on 2024-02-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unwind', '0002_remove_music_cover_remove_music_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
