# Generated by Django 5.0.2 on 2024-02-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unwind', '0003_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('music', models.FileField(upload_to='Music')),
                ('cover', models.FileField(upload_to='Music/Cover')),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unwind.musiccategory')),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unwind.mood')),
            ],
        ),
    ]
