# Generated by Django 5.0 on 2024-02-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('stories', models.TextField()),
                ('pic', models.FileField(upload_to='Img')),
            ],
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
