# Generated by Django 5.0 on 2024-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspire', '0002_story_delete_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pic',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
